---
plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - spec/**/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/jenkins-peace.rb

Layout/LineLength:
  Exclude:
    - jenkins-peace.gemspec
