language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - jruby-9.2.9.0
env:
  global:
    - JRUBY_OPTS="--debug"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
